### ISSUE TITLE
gdal package required 

### ISSUE THREAD

**Issue by dch1fc** [cedadev/ceda-jaspy-envs#142]
Hi there,

I have a Python script that works with previous jaspy e.g. jaspy/3.8/r20211105 but failed with the default version of  jaspy/3.10/r20230718.

Can you add the gdal package in the future  jaspy release? 

Thank you

**Comment by alaniwi** [comment]
gdal package is already present (now at jaspy/3.11/r20240508 and was also at version jaspy/3.10/r20230718).

See for example 
```
/apps/jasmin/jaspy/miniforge_envs/jaspy3.11/mf3-23.11.0-0/envs/jaspy3.11-mf3-23.11.0-0-r20240508/conda-meta/gdal-3.8.4-py311h8be719e_0.json

/apps/jasmin/jaspy/mambaforge_envs/jaspy3.10/mf-22.11.1-4/envs/jaspy3.10-mf-22.11.1-4-r20230718/conda-meta/gdal-3.5.2-py310hb7951cf_3.json
```

**Comment by alaniwi** [comment]
Closing this ticket. If you find another package that is needed for that script to work, please open a separate ticket.
