### ISSUE TITLE
add "parcels"

### ISSUE THREAD

**Issue by gmacgilchrist** [cedadev/ceda-jaspy-envs#144]
Would you consider adding the [Ocean Parcels package](https://github.com/OceanParcels/parcels) to the Jaspy environment? The software allows the tracking of particles in an ocean circulation model. As far as I can tell, many of its dependencies are already present.

**Comment by alaniwi** [comment]
I have confirmed that `mamba install parcels` in a new, empty environment will install the package, and that the example code at https://docs.oceanparcels.org/en/latest/examples/parcels_tutorial.html can then be run successfully (as far as producing the first plot shown).

This produces a conda environment of size 1.3GB, with ~37k files. However, comparing the size of the Jaspy environment with and without adding `parcels` shows that it only _increases_ the size by 67MB and ~500 files (on top of the existing ~10GB, ~250k files), as per your observation that many of the dependencies are already present. So this is fine.

It will probably be of order a few months until the next Jaspy release as there has been one recently, so in the meantime you may have to use your own private conda environment. I see that you have submitted a helpdesk ticket, so I will reply to that with some details.

**Comment by alaniwi** [comment]
Added to jaspy release 20240815 currently under preparation -- should be available for users soon. Now closing ticket.
