### ISSUE TITLE
Keras and TensorFlow

### ISSUE THREAD

**Issue by pui-nantheera** [cedadev/ceda-jaspy-envs#15]
Hi,

I'm working on deep learning using Keras (running on top of TensorFlow). I cannot find whether these two have been installed. Can you please add them in?

Thanks.

**Comment by alaniwi** [comment]
Responding to this old ticket.

Various packages had been added in a previous Jaspy release but then removed, presumably due to dependency issues. The environment now seems to resolve okay with them in, so readding them (unless another problem is later encountered). These are:

```
    - dask-tensorflow
    - keras
    - tensorflow
    - tensorflow-estimator
```

**Comment by alaniwi** [comment]
Removing `dask-tensorflow` again.

**Comment by alaniwi** [comment]
It turned out that it was possible to readd the `keras`, `tensorflow` and `tensorflow-estimator` packages. These will be included in the forthcoming release. However, the `dask-tensorflow` package (possibly unrelated to the requested package) remains excluded. Closing.
