### ISSUE TITLE
add pymc3

### ISSUE THREAD

**Issue by alaniwi** [cedadev/ceda-jaspy-envs#16]
Moved from ticket #131 where it was originally requested.

Dependencies which would need added first:
```
patsy
theano
joblib
tqdm
enum34
```

Otherwise appears to build cleanly (RPM built already although missing RPM dependencies), but requires patch to requirements.txt and fails at import time while dependencies are missing.

**Comment by agstephens** [comment]
Available on conda-forge. Needs testing in: 

jaspy3.7-m3-4.6.14-r20190703

**Comment by agstephens** [comment]
Test works in latest Jaspy.
