### ISSUE TITLE
Please add openair (R package)

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-jaspy-envs#17]
If it is trivial to add then please include the "openair" R package in the JAP. See installation one-liner at:

http://www.openair-project.org/GettingStarted/Default.aspx

**Comment by alaniwi** [comment]
Updating this old ticket. Although there were issues with providing RPM packages as described above, now that we are using a conda environment for  `jasr` this can be installed from the package `r-openair`, so we will aim to do this.

**Comment by alaniwi** [comment]
Adding `r-openair` to Spring 2023 Jasr release. Closing this issue.
