### ISSUE TITLE
Install R "sf" packages: r-sf, r-sfheaders, r-sfsmisc

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-jaspy-envs#2]
Migrated from:

https://github.com/cedadev/jasmin_scivm/issues/169

Tagging: 
@philor-CEH , @alaniwi 

Should be able to use latest "jaspy" on JASMIN and this should work:

```
module load jaspy/3.7/r20190627
R
> install.packages("sf")
```

**Comment by alaniwi** [comment]
a recent CEDA helpdesk query confirmed that using a more recent C compiler fixes `sf` installation issues

**Comment by agstephens** [comment]
Need a test case before we close this.

**Comment by agstephens** [comment]
This installs in the latest jaspy. It takes about 5 minutes, and requires *manual intervention* to accept/specify which repo/dir to install with.

Need to add some test code before we close it, after:

```
R
> install.packages("sf")
```

**Comment by agstephens** [comment]
Preferred approach, will be to try to install from conda-forge:

- r-sf
- r-sfheaders
- r-sfsmisc

**Comment by alaniwi** [comment]
Environment resolves including `r-sf`, `r-sfheaders`, `r-sfsmisc`.

**Comment by alaniwi** [comment]
These were added
