### ISSUE TITLE
cf-checker: update and change dependencies

### ISSUE THREAD

**Issue by alaniwi** [cedadev/ceda-jaspy-envs#22]
Update cf-checker. Also note new version uses netCDF4 instead of CDMS, so reflect in RPM dependencies.

**Comment by agstephens** [comment]
Need to ensure that a version of the cf-checker is available - might need to stick with Python2.7.

**Comment by martinjuckes** [comment]
Latest version of the cf-checker appears to require python3 -- the latest cf-checker package doesn't work in the `jaspy` environment at the moment because it requires the pypi `future` package (supplying the `past` module).

**Comment by agstephens** [comment]
Thanks @martinjuckes, we are trying to overcome some `conda` problems that have delayed the roll-out of a new `jaspy` environment, which would include the latest cf-checker.

**Comment by martinjuckes** [comment]
@agstephens : thanks, that is good to know ... any idea how severe these `conda` problems are? Is it a matter of days or weeks?

**Comment by alaniwi** [comment]
Seems that the current installation is still broken. Not present in jaspy/3.7, and the installation in jaspy/2.7 says that it needs python 3 when you try to run it (`module load jaspy/2.7; cfchecks`). Specifically this is a version error on `cfunits`

```
[username@sci1 ~]$ which python
/apps/contrib/jaspy/miniconda_envs/jaspy2.7/m2-4.6.14/envs/jaspy2.7-m2-4.6.14-r20190715/bin/python

[username@sci1 ~]$ python -c 'import cfunits'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/apps/contrib/jaspy/miniconda_envs/jaspy2.7/m2-4.6.14/envs/jaspy2.7-m2-4.6.14-r20190715/lib/python2.7/site-packages/cfunits/__init__.py", line 34, in <module>
    minimum_vn,  platform.python_version()))
ValueError: Bad python version: cf requires python version 3.0.0 or later. Got 2.7.15
```
Though maybe this is already known.

**Comment by agstephens** [comment]
Hi @martinjuckes,

I'm trialing a new Jaspy installation. Please can you test the cfchecker works okay (at v4.0.0) if you run it with:

```
ssh <username>@sci2.jasmin.ac.uk
source /apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/bin/activate jaspy3.7-m3-4.6.14-r20200226
cfchecks <nc_file>
```

Thanks

**Comment by alaniwi** [comment]
Assuming fixed now - `cfchecks` works fine in existing Jaspy when I test it, and no word to the contrary. Closing.
