### ISSUE TITLE
pyferret

### ISSUE THREAD

**Issue by alaniwi** [cedadev/ceda-jaspy-envs#24]
pyferret has now been requested by a user. (FP ticket 41157.)

Previous attempts to try to build were not successful, but I gave up relatively early because there had been no request. Maybe revisit this, now that there is an explicit request.

Notes from the previous attempt can be seen at http://proj.badc.rl.ac.uk/cedaservices/ticket/696

**Comment by agstephens** [comment]
Seems to install fine in: jaspy3.7-m3-4.6.14-r20190703
Need to add a simple test.

```
import os
import pyferret
pyferret.start(quiet=True)
import shutil

import iris_sample_data
fname = 'A1B_north_america.nc'
srcpath = os.path.join(iris_sample_data.path, fname)
ncpath = os.path.join('/tmp', fname)

shutil.copy(srcpath, ncpath)

ds = pyferret.FerDSet(ncpath)
assert(ds['height'].unit == 'm')
assert(ds['air_temperature'].data.shape == (49, 37, 1, 240, 1, 1))
```

**Comment by agstephens** [comment]
Working in current jaspy.
