### ISSUE TITLE
add ANTS

### ISSUE THREAD

**Issue by alaniwi** [cedadev/ceda-jaspy-envs#3]
A user requested:

"""
I will need a python package for changing the resolution of some of the ancillary files on JASMIN to start running models for the ISIMIP.

Would it be possible to centrally install the package called ANTS?

Please, find more information about it on the following links.

https://code.metoffice.gov.uk/trac/ancil/wiki/ANTS/Setup

https://code.metoffice.gov.uk/doc/ancil/ants/latest/install.html
"""

**Comment by agstephens** [comment]
Asked HD whether ANTS is even Py3-compatible.

**Comment by agstephens** [comment]
Should be discussed separately with the MO (metomi) team.

**Comment by alaniwi** [comment]
Old ticket, but a request for this came up more recently. Without seeing that it was a dup, I closed that ticket (#107) as WONTFIX because user had not supplied enough information to locate the package. However, above are links. But I have lost my access to the Met Office code repo ("user [username] is not active").

**Comment by alaniwi** [comment]
I now see that Simon Wilson is providing this via his JASMIN home directory, per https://cms.ncas.ac.uk/miscellaneous/ants-container/  Maybe this can put in `/apps/jasmin/community` (I'll suggest it to him), but I am now closing this ticket.
