### ISSUE TITLE
R package igraph fails to compile

### ISSUE THREAD

**Issue by pboesu** [cedadev/ceda-jaspy-envs#31]
I am trying to install the R package igraph within the jaspy/3.7/r20190627 environment, but the compilation fails because of issues with the CHOLMOD headers (some of the errors/warnings below). 

```
CHOLMOD/Check/cholmod_check.c:84:29: error: 'cholmod_common {aka struct cholmod_common_struct}' has no member named 'print_function'
     if (print >= i && Common->print_function != NULL) \
                             ^
CHOLMOD/Check/cholmod_check.c:92:24: note: in expansion of macro 'PR'
 #define P3(format,arg) PR(3,format,arg)
                        ^~
CHOLMOD/Check/cholmod_check.c:2204:5: note: in expansion of macro 'P3'
     P3 ("%s", "  OK\n") ;
     ^~
CHOLMOD/Check/cholmod_check.c:86:9: error: 'cholmod_common {aka struct cholmod_common_struct}' has no member named 'print_function'
  (Common->print_function) (format, arg) ; \
         ^
CHOLMOD/Check/cholmod_check.c:92:24: note: in expansion of macro 'PR'
 #define P3(format,arg) PR(3,format,arg)
                        ^~
CHOLMOD/Check/cholmod_check.c:2204:5: note: in expansion of macro 'P3'
     P3 ("%s", "  OK\n") ;
     ^~
```

The igraph package compiles fine on `jasmin-sci1-test` with `devtoolset-6` enabled, so I believe this is because of a conflicting header being provided by the conda environment (analoguous to this issue reported for homebrew: https://github.com/igraph/rigraph/issues/135). 

Any ideas how to resolve this? 

Compiling igraph one-off on sci1-test is not a solution, as I ultimately I want to compile stan models from R sessions on JASMIN/LOTUS on the fly which requires a C++14 compatible compiler. Using the jaspy environment seemed like a convenient avenue to do this.
Alternatively, is there a way to let R access recent gcc/g++ versions on JASMIN/LOTUS (e.g. via .R/Makevars)?

**Comment by agstephens** [comment]
Testing installing this in next jaspy env.

**Comment by pboesu** [comment]
Thanks! 
Relatedly - are there plans to enable the use of contemporary g++ compilers (i.e. C++14 compatible) in the new CentOS setup. Having these available on the sci-nodes and LOTUS would be immensely useful to me.

**Comment by agstephens** [comment]
Hi @pboesu , regarding compilers on JASMIN. Please see this page for details of compilers that are provided in the new CentOS7 builds:

https://help.jasmin.ac.uk/article/4896-how-to-submit-an-mpi-parallel-job-to-slurm

**Comment by agstephens** [comment]
Closing - we can discuss compilers elsewhere.
