### ISSUE TITLE
basemap-data-hires using conda-forge

### ISSUE THREAD

**Issue by ogersentia** [cedadev/ceda-jaspy-envs#33]
Hello,
Could you please add basemap-data-hires using conda-forge ?
Regards,
Sentia Goursaud

**Comment by agstephens** [comment]
Hi @aitens , I am trying out a new build that includes `basemap-data-hires`. Assuming it resolves okay, do you have a short function/script to add as a test for the use of that package? Many thanks

**Comment by aitens** [comment]
Thank you for handling my request. I had written the python script given below, which is actually the one which returned me the message "OSError: Unable to open boundary dataset file. Only the 'crude' and  'low',
resolution datasets are installed by default.
If you are requesting an, 'intermediate', 'high' or 'full'
resolution dataset, you may need to download and install those
files separately with
`conda install -c conda-forge basemap-data-hires`."
I have just tried it again, but it returned the same message. 
Here is the code:

#!/usr/bin/python
# -*- coding: utf-8 -*-
import numpy as np
from netCDF4 import Dataset,num2date, date2num, date2index
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.axes as ax
from mpl_toolkits.basemap import Basemap,shiftgrid,maskoceans,addcyclic
matplotlib.use('Agg')

path = '/home/users/mholloway/xjoad.d18Opw.10yrs.annual.nc'
var_name='d18O'
label = r'$\delta^{18} O$'+u' ('+u'\u2030'+')' 

f = Dataset(path)
var = f.variables[var_name][:,:]#[0,0,:,:]
lat = f.variables['latitude'][:]
lon = f.variables['longitude'][:]
f.close()

fig = plt.figure()
m=Basemap(projection='spstere',boundinglat=-60,lon_0=-180,resolution='h')
var_cyclic,lon_cyclic = addcyclic(var,lon)
var_cyclic,lon_cyclic = shiftgrid(180.,var_cyclic,lon_cyclic,start=False)
lon2d,lat2d=np.meshgrid(lon_cyclic,lat)
x,y=m(lon2d,lat2d)
mdata=maskoceans(lon2d,lat2d,var_cyclic,resolution='h',grid=1.25,inlands=True)
cs=m.contourf(x,y,mdata,cmap=plt.cm.rainbow,alpha=0.5)
levels = np.arange(var.min(),var.max(),5)
cs2 = m.contour(x,y,mdata,levels=levels,linewidth=1.)
plt.clabel(cs2,fmt='%4.0f',fontsize=8)
m.drawcoastlines(color='grey')
m.drawmapboundary()
cbar=m.colorbar(cs,location='bottom')
cbar.set_label(label)
cbar.ax.tick_params(labelsize=8)
plt.show()

**Comment by agstephens** [comment]
Hi @aitens ,

Apologies for the delay in getting back to you.

I have managed to get a new Jaspy version built which includes `basemap-data-hires`. However, it is not yet officially available and I need people to test out the functionality with some real applications.

Please can you test out this environment on one of our new CentOS7 servers. You can get logged in and set up the environment with:

```
ssh <username>@sci2.jasmin.ac.uk
source /apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/bin/activate jaspy3.7-m3-4.6.14-r20200226
```

Please do some testing and let me know if it works for you.

Thanks

**Comment by alaniwi** [comment]
This was provided in the current default Jaspy. Closing.
