### ISSUE TITLE
remove broken emacs from jaspy2.7

### ISSUE THREAD

**Issue by alaniwi** [cedadev/ceda-jaspy-envs#34]
emacs is broken in Jaspy/2.7

```
emacs: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```

It is probably also unnecessary, because on JASMIN, the machines with access to Jaspy also have emacs locally installed.

I suggest removing it.

**Comment by agstephens** [comment]
This will be phased out soon so ignore.
