### ISSUE TITLE
Cartopy fails to display from Jupyter environment

### ISSUE THREAD

**Issue by philipkershaw** [cedadev/ceda-jaspy-envs#39]
Simple Cartopy example fails to display from Jupyter environment on JASMIN - ran code adapted from this sample:

https://scitools.org.uk/cartopy/docs/latest/gallery/global_map.html#sphx-glr-gallery-global-map-py

The code works fine with standalone CLI script run with conda

**Comment by agstephens** [comment]
@mkjpryor-stfc : this also works fine on a JASMIN "sci" server so the issue presumably relates to something in the Jupyter container setup.

**Comment by mkjpryor-stfc** [comment]
Not a Jaspy issue.
