### ISSUE TITLE
R update 

### ISSUE THREAD

**Issue by bearecinos** [cedadev/ceda-jaspy-envs#42]
Hello,

according to the List of packages included in [here](https://github.com/cedadev/ceda-jaspy-envs/blob/master/environments/py3.7/m3-4.5.11/jaspy3.7-m3-4.5.11-r20181219/initial.yml) the R version there is slightly old. 
Would it be possible to update this to an R version say 3.6.3 or latest?

Thank you

**Comment by agstephens** [comment]
@bearecinos thanks for the request. We are working on a new release and we'll include this if there are no problems in doing so. Thanks

**Comment by agstephens** [comment]
@bearecinos,

Apologies for the delay in getting back to you.

I have managed to get a new Jaspy version built which includes R at version 3.6.3. However, it is not yet officially available and I need people to test out the functionality with some real applications.

Please can you test out this environment on one of our new CentOS7 servers. You can get logged in and set up the environment with:

```
ssh <username>@sci2.jasmin.ac.uk
source /apps/contrib/jaspy/miniconda_envs/jaspy3.7/m3-4.6.14/bin/activate jaspy3.7-m3-4.6.14-r20200226
```

Please do some testing and let me know if it works for you.

Thanks

**Comment by bearecinos** [comment]
Thanks it works fine!

**Comment by agstephens** [comment]
Thanks @bearecinos , that's great.
