### ISSUE TITLE
Package request: Pygeode

### ISSUE THREAD

**Issue by admg26** [cedadev/ceda-jaspy-envs#43]
PyGeode is a python package intended to simplify the manipulation, analysis and visualization of geophysical datasets, such as those generated by climate models. 

I believe the previous JAP platform with python 2 had support for pygeode.

Documentation: http://pygeode.github.io/

The package is available here: https://pypi.org/project/pygeode/

I use this package in my own conda environment on JASMIN but would like to be able to access it via the JASMIN notebook service.

**Comment by agstephens** [comment]
Hi @admg26 , we have a new Jaspy environment that includes Pygeode installed via Pip. However, it is not likely to be included in the Notebook service for a while. In the short-term, please try using the approach described in the following Notebook which allows you to create a `virtualenv` from within your Notebook, and then you can Pip install extra packages:

https://github.com/cedadev/ceda-notebooks/blob/master/notebooks/virtualenvs-on-jasmin.ipynb

Please let me know if it works for you.

**Comment by admg26** [comment]
Hi @agstephens, I've tried this but then hit a weird issue with libnetcdf not being installed. This is what I have done in a command line running Python 3 + Jaspy. 
https://pastebin.com/fhtYw0Nw

**Comment by agstephens** [comment]
@admg26 , I have created a notebook that appears to work on our Notebook server:

https://github.com/agstephens/ceda-notebooks/blob/master/notebooks/pygeode-virtualenv.ipynb

Does that work for you? Thanks

**Comment by admg26** [comment]
All of this work up to the point where I try to use pygeode to open a netcdf file. pygeode depends on this: https://pypi.org/project/netcdf/

```
import pygeode as pyg
A = pyg.open('./data/o3col_control_clim.nc')
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-e1b34d4123a9> in <module>
----> 1 A = pyg.open('./data/o3col_control_clim.nc')

~/nb-venvs/venv-notebook/lib/python3.7/site-packages/pygeode/formats/__init__.py in open(filename, format, value_override, dimtypes, namemap, varlist, cfmeta, **kwargs)
    155   if not hasattr(format, 'open'):
    156     try:
--> 157       format = __import__("pygeode.formats.%s" % format, fromlist=["pygeode.formats"])
    158     except ImportError:
    159       raise ValueError('Unrecognized format module %s.' % format)

~/nb-venvs/venv-notebook/lib/python3.7/site-packages/pygeode/formats/netcdf.py in <module>
      4 from ctypes import c_char_p
      5 from pygeode.libhelper import load_lib
----> 6 lib = load_lib('netcdf')
      7 lib.nc_strerror.restype = c_char_p
      8 del c_char_p

~/nb-venvs/venv-notebook/lib/python3.7/site-packages/pygeode/libhelper.py in load_lib(name, Global)
     69 #  if exists(name) and '/' not in name: name = './' + name
     70   libname = find_library (name)
---> 71   assert libname is not None, "can't find library '%s'"%name
     72 #  print "debug: '%s' => '%s'"%(name, libname)
     73 

AssertionError: can't find library 'netcdf' 
```

**Comment by admg26** [comment]
Hi,

After the pygeode pip wheel was rebuild to decouple the two dependencies, it now works!
