### ISSUE TITLE
R package 'renv'

### ISSUE THREAD

**Issue by hsteptoe** [cedadev/ceda-jaspy-envs#47]
Could you consider making the R package `renv` generally available on the jaspy environment?  The main benefit is that `renv` is to R what `venv` is to python, so it would allow folk to customise their own R environment in a similar way to freedom we have to create our own python environments. It also brings the benefits of `venv` such as portability and reproduciblity of code etc.

More info about `renv` here https://rstudio.github.io/renv/ 

Thanks!

**Comment by alaniwi** [comment]
We will try to add the conda package `r-renv`, providing that this does not break any tests.

**Comment by alaniwi** [comment]
Done.
