### ISSUE TITLE
R package "maps"

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-jaspy-envs#48]
Can we install "maps" for R, see:

https://secure.helpscout.net/conversation/1287931402/38435?folderId=3874196

Test with:

```
library(maps)
​
​# test with
​map.cities
```

**Comment by alaniwi** [comment]
conda package `r-maps`. Environment resolves but test needs to be added per above.

**Comment by alaniwi** [comment]
Above test just prints the function. Testing with `map.cities()` by itself gives blank map. Can test with 

```
map("world", "UK")
map.cities()
```

(Slightly messy because it also shows cities outside the UK within the plot area, but not worth refining.)

**Comment by alaniwi** [comment]
Done.
