### ISSUE TITLE
xxdiff on JASMIN 

### ISSUE THREAD

**Issue by caroduro** [cedadev/ceda-jaspy-envs#5]
xxdiff is a very handy graphical interface to compare folders as well as files. 
Would you please be able to install it on JASMIN platform?

**Comment by alaniwi** [comment]
Unfortunately we get this installed. `pip install` appears to complete but installs a python module only with no command-line entry points.

The "diffuse" program provided with jasmin-sci (`module load jasmin-sci`, then type `diffuse`) does a similar function.

(There is also tkdiff, although that is more clunky.)

Additionally, emacs provides "ediff" (press alt-X and type `ediff-buffers`), with again similar functionality.

In view of the range of other options, closing as WONTFIX.
