### ISSUE TITLE
updates to jaspy environment

### ISSUE THREAD

**Issue by MareikeJaniak** [cedadev/ceda-jaspy-envs#51]
Good afternoon, 

I am a postdoc with a NERC-funded project on genomics of platyrrhine primates. Our groups workspace 'rotcotm' is new to JASMIN, but we look forward to working with the available resources.

Would it be possible to add the following packages to the jaspy environment? I realize that we might be the only group working with genomic data at the moment, so a lot of the basic tools are not yet included in jaspy. Please let me know if any this presents any issues. 

Packages:
bbmap 38.87 https://anaconda.org/bioconda/bbmap
mafft 7.471 https://anaconda.org/bioconda/mafft
blast 2.10.1 https://anaconda.org/bioconda/blast
velvet 1.2.10 https://anaconda.org/bioconda/velvet
exonerate 2.4.0 https://anaconda.org/bioconda/exonerate
bowtie2 2.4.2 https://anaconda.org/bioconda/bowtie2
fastqc 0.11.9 https://anaconda.org/bioconda/fastqc
bedtools 2.29.2 https://anaconda.org/bioconda/bedtools
MrBayes 3.2.7 https://anaconda.org/bioconda/mrbayes
RaxML 8.2.12 https://anaconda.org/bioconda/raxml
BEAST 1.10.4 https://anaconda.org/bioconda/beast
BEAST2 2.6.3 https://anaconda.org/bioconda/beast2
Phyluce 1.6.8 https://anaconda.org/bioconda/phyluce
Samtools 1.11 https://anaconda.org/bioconda/samtools
bamtools 2.5.1 https://anaconda.org/bioconda/bamtools
BCFtools 1.11 https://anaconda.org/bioconda/bcftools

Thanks!
Best, 
Mareike

**Comment by MareikeJaniak** [comment]
Good morning, 

I just wanted to amend my request above with a new version of RaxML that has just recently become available:
Instead of RaxML 8.2.12, RaxML-NG 1.0.1 (https://anaconda.org/bioconda/raxml-ng)

Best, 
Mareike

**Comment by igoodhead** [comment]
Hello there,

I wonder if I could request an update on this, please? We have just received an email from the JASMIN helpdesk that there will be an update freeze after 11 Dec, and are keen to process any updates prior to this, if at all possible.

I'll also pop this into an email, with apologies for duplication, in case this is/has been missed.

Thank you, and kind regards,
Ian
(Co-I: NERC Rise of the Continent of the Monkeys (rotcotm))

**Comment by MareikeJaniak** [comment]
Good morning, 
I've been able to install most packages in conda environments in my home directory, so I'm closing the issue. 

Best, 
Mareike
