### ISSUE TITLE
xgcm and xhistogram in jaspy

### ISSUE THREAD

**Issue by hmkhatri** [cedadev/ceda-jaspy-envs#88]
Would it possible to install [xgcm](https://xgcm.readthedocs.io/en/latest/) add [xhistogram](https://xhistogram.readthedocs.io/en/latest/) packages in the latest Jaspy environment?

These packages are being used widely for analysing large ocean model outputs and CEDA/JASMIN users might find it helpful to have these packages installed in Jaspy environments.

**Comment by alaniwi** [comment]
These are ready for installation in the next Jaspy release - hopefully soon - which is why I am closing this issue now.
