### ISSUE TITLE
Dask JupyterLab Extension for Jasmin notebook service

### ISSUE THREAD

**Issue by hmkhatri** [cedadev/ceda-jaspy-envs#89]
It would be useful to have [Dask lab-extension](https://github.com/dask/dask-labextension) installed on Jasmin notebook service for testing parallel computations on inbuilt dask dashboard.

**Comment by agstephens** [comment]
Thanks @hmkhatri , we will look into this for the next release.

**Comment by agstephens** [comment]
@hmkhatri, we currently have users testing a system that employs `dask-gateway` to broker tasks between the Notebook Service and the LOTUS batch compute cluster. The dask-gateway web-interface includes a dashboard for viewing and monitoring the parallel running of jobs via dask. Please contact support@ceda.ac.uk for more details.
