### ISSUE TITLE
Collect up all imports from the ceda-notebooks repo and try to ensure they are all installed

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-jaspy-envs#95]
- [ ] Clone the ceda-notebooks repo
- [ ] Find an appropriate `grep` (or search) that will look for all imported libraries within the notebooks
- [ ] Add an issue for each new package that we need to install.

**Comment by alaniwi** [comment]
list of all modules imported from:

```
cartopy.crs
cartopy.feature
csv
fixnc
fsspec
gdal
intake
intake_esm
math
matplotlib.colors
matplotlib.dates
matplotlib.pyplot
mpl_toolkits.basemap
netCDF4
numpy
os
osr
pandas
pyam
scipy
scripts
scripts.utils
seaborn
sklearn.cluster
sklearn.decomposition
sklearn.preprocessing
sys
warnings
xarray
```

**Comment by alaniwi** [comment]
Missing imports are:

 - `fixnc` - this is meant not to import (notebook demonstrates use of a venv)
 - `pyam` - same as for `fixnc`
 - `scripts` and `scripts.utils` - these are imports from the notebooks repo itself

Therefore, there are no missing imports, and no new issues to add as a consequence.
