### ISSUE TITLE
Version >1.5-12 of R package terra on jasr

### ISSUE THREAD

**Issue by simonrolph** [cedadev/ceda-jaspy-envs#97]
Could we please update R package `terra` on jasr to version 1.5-12 or later. The current version on jasr is 1.4-11 https://github.com/cedadev/ceda-jaspy-envs/blob/aae47495238747e3b38c2928779b863e7dacb87b/environments/r4.0/m3-4.9.2/jasr4.0-m3-4.9.2-r20211110/packages.txt#L1057

I am encountering an issue about running terra on slurm, similar to this: https://github.com/rspatial/terra/issues/476 which means I'm getting out of memory errors.

Version 1.5-12 contains an update to `terra` which allows a setting to provide a maximum memory limit. Any version later than that would be great. Latest version on CRAN is 1.5-21.

Thanks

**Comment by agstephens** [comment]
@alaniwi Just checking you have seen this one.

**Comment by alaniwi** [comment]
Closing.

Autumn 2022 release specified `>=1.5_12` as requested, and actually had `1.5.21`
Furthermore, Spring 2023 release (in preparation) specifies `>=1.5.21` and actually has `1.7_23`
